version: '3.7'
services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    container_name: mongo_miaguila
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: api_miaguila
    depends_on:
      - database